apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: weather-ui
    name: weather-ui
    type: web
  name: weather-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-ui
      name: weather-ui
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: weather-ui
        name: weather-ui
        type: web
      name: weather-ui
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        imagePullPolicy: IfNotPresent
        name: weather-ui
        ports:
        - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
